### ISSUE TITLE
Make jdleden use a local hemres instance

### ISSUE THREAD

**Issue by Pi2048** [jonge-democraten/jdleden#1]
In the new server setup, jdleden will run on a different server from the one running hemres. Therefore, it needs to directly access the database instead of through the website setup.

The problem is: Django does not give any guarantees about the database structure. It could change significantly and without warning between versions. Therefore, jdleden should not include any code that presumes to know the database structure.

The ideal solution would be to have a local copy of hemres within the virtualenv of jdleden. Then, jdleden could call the right functionality directly instead of through manage.py. I tried to implement it, but I got lost between the different options and modules.

@bartromgens, @trolando could one of you refactor jdleden to call its own local instance of hemres? Thank you!

**Comment by bartromgens** [comment]
Making jdleden directly call hemres requires, as far as I understand, jdleden to be a Django project (with manage.py and settings.py); jdleden would become a management command. This is fine because all our apps are based on Django.

However, hemres depends on Mezzanine and Janeus (note: these dependencies are currently not defined in setup.py of hemres),
- Mezzanine is needed in hemres for `SiteRelated` from which `Newsletter` is derived, although most likely not needed by jdleden. 
- Janeus is probably not used by jdleden, but not sure.

Depending on Mezzanine and/or Janeus is not an implementation problem. However, Mezzanine is rather demanding and requires some settings to be set, which would be dummies, and can change in the future. 
From a jdleden perspective, depending on Mezzanine introduces unnecessary future maintenance and complexity.
Removing the Mezzanine dependency requires a split in hemres between the Newsletter and the rest. This is also not free of maintenance. 

I am fairly confident we can make this change, but I want to be sure this is what we really want before starting the work.

**Comment by trolando** [comment]
Indeed, hemres is more tightly integrated now, although for some time the integration was sorta optional. Maybe setup.py should be updated to reflect this, indeed.

I did receive the email I received from @Pieter1024 on this, haven't gotten time yet to really look into this.

What if jdleden would generate a JSON string that could be sent to the server via some management command?

**Comment by Pi2048** [comment]
Let's discuss this over the weekend.

**Comment by Pi2048** [comment]
@bartromgens is making good progress on this. Bart, could you tell us what the status of your work is?

**Comment by bartromgens** [comment]
jdleden is now a Django project and calls Hemres directly. jdleden is now used via its management commands, as documented in the readme.

While at it, I refactored some code, created test data, automated (unit)tests, and build automation (travis-ci).

There are some minor tasks left before this is truly done,
- [x] document which settings in `settings.py` are just dummies.
- [ ] document all functions
- [x] create some additional unit tests
- [x] create a `build_env.sh` and `clean_env.sh`, just like our other Django projects

**Comment by Pi2048** [comment]
Thanks for the update! This issue blocks the migration of our website to the new VPS. I think none of the remaining tasks you mention is required to deploy the new code to production, right?

**Comment by bartromgens** [comment]
> I think none of the remaining tasks you mention is required to deploy the new code to production, right?

Correct. jdleden is independent of the website and only talks to the database and LDAP server.

I have to run a real jdleden update to see if everything works as expected in production, but that should not hold us back from moving the website.

**Comment by Pi2048** [comment]
Good, thanks. I will then proceed to move the website. I take it you will not run the old jdleden anymore? That would be excellent.

**Comment by bartromgens** [comment]
I will not run the old jdleden anymore.

**Comment by bartromgens** [comment]
All minor tasks are now also done. Time to close this issue.
